Write username to /tmp

diff --git a/apps/x86_64-linux/install b/apps/x86_64-linux/install
--- a/apps/x86_64-linux/install
+++ b/apps/x86_64-linux/install
@@ -23,6 +23,11 @@ download_config() {
 
 run_apply() {
   /mnt/etc/nixos/bin/apply
+  if [ ! -f /tmp/username.txt ]; then
+    echo -e "\e[1;31mError: /tmp/username.txt does not exist.\e[0m"
+    exit 1
+  fi
+  export USERNAME=$(cat /tmp/username.txt)
 }
 
 run_disko() {
diff --git a/apps/x86_64-linux/installWithSecrets b/apps/x86_64-linux/installWithSecrets
--- a/apps/x86_64-linux/installWithSecrets
+++ b/apps/x86_64-linux/installWithSecrets
@@ -22,7 +22,12 @@ download_config() {
 }
 
 run_apply() {
-  /mnt/etc/nixos/bin/apply # Sets $USERNAME
+  /mnt/etc/nixos/bin/apply
+  if [ ! -f /tmp/username.txt ]; then
+    echo -e "\e[1;31mError: /tmp/username.txt does not exist.\e[0m"
+    exit 1
+  fi
+  export USERNAME=$(cat /tmp/username.txt)
 }
 
 run_disko() {
@@ -41,6 +46,7 @@ setup_files() {
 }
 
 setup_ssh_keys() {
+
   mkdir -p /mnt/home/${USERNAME}/.ssh
   chown nixos /mnt/home/${USERNAME}/.ssh
 
@@ -48,7 +54,7 @@ setup_ssh_keys() {
   cp --preserve=all /root/.ssh/id_ed25519_agenix /mnt/home/${USERNAME}/.ssh/id_ed25519
   cp --preserve=all /root/.ssh/id_ed25519_agenix.pub /mnt/home/${USERNAME}/.ssh/id_ed25519.pub
 
-  chmod 600 /mnt/home/${user}/.ssh/id_ed25519{,.pub}
+  chmod 600 /mnt/home/${USERNAME}/.ssh/id_ed25519{,.pub}
 }
 
 link_home_dir() {
@@ -73,7 +79,7 @@ check_installer
 download_config
 run_disko
 setup_files
-run_apply  # Sets $USERNAME
+run_apply
 setup_ssh_keys
 link_home_dir
 install_nixos
