Update test-nix-flake.yml

diff --git a/.github/workflows/test-nix-flake.yml b/.github/workflows/test-nix-flake.yml
--- a/.github/workflows/test-nix-flake.yml
+++ b/.github/workflows/test-nix-flake.yml
@@ -4,9 +4,13 @@ on:
   push:
     branches:
       - main
+    paths:
+      - 'flake.nix' 
   pull_request:
     branches:
       - main
+    paths:
+      - 'flake.nix'
 
 jobs:
   nix-flake-build:
@@ -35,13 +39,11 @@ jobs:
     - name: Build Nix Flake
       run: |
         cd /home/runner/work/nixos-config/nixos-config/my-config
-        echo "Listing current directory:"
-        ls -la
         git add .
         echo "Building Flake..."
         nix build --extra-experimental-features 'nix-command flakes' /home/runner/work/nixos-config/nixos-config/my-config#nixosConfigurations."x86_64-linux".config.system.build.toplevel
         if [ $? -ne 0 ]; then
-        echo "Build failed, listing flake.lock for debugging:"
-        cat flake.lock
-        exit 1
+          echo "Build failed, listing flake.lock for debugging:"
+          cat flake.lock
+          exit 1
         fi
